version: '3.8'

services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "80:80"
    networks:
      - dcompose
    environment:
      - BACKEND_SERVICE_URL=http://backend:8080

  backend:
    build: ./backend
    image: backend
    ports:
      - "8080:8080"
    networks:
      - dcompose

networks:
  dcompose:
    driver: bridge
